describe('template spec', () => {
  it('passes', () => {
    
    cy.visit('https://www.google.com/search?q=calculator')

    cy.type_number("2247402096488*+-+//**")
    cy.check_answer("2247402096488 ×")
    cy.check_history('Ans = 0')
    cy.clickButton_equal()
    cy.check_answer("2247402096488 ×")
    cy.check_history('Ans = 0')
    cy.type_number("........")
    cy.check_answer("2247402096488 × .")
    cy.check_history('Ans = 0')
    cy.clickButton_equal()
    cy.check_answer("Error")
    cy.type_number("*/++/+")
    cy.check_answer("0 +")
    cy.check_history('Ans = 0')
    cy.clickButton_equal()
    cy.check_answer("0 +")
    cy.check_history('Ans = 0')
    cy.type_number("*+*-//**+-+-+/")
    cy.check_answer("0 × -")
    cy.check_history('Ans = 0')
    cy.type_number("0000000000...........000000000")
    cy.clickButton_equal()
    cy.AC_expected()
    cy.check_answer("0")
    cy.check_history('0 × -0.000000000 =')
    cy.type_number("------24667")
    cy.CE_expected()
    cy.check_answer("0 - 24667")
    cy.check_history('Ans = 0')
    cy.clickButton_equal()
    cy.check_answer("-24667")
    cy.check_history("0 - 24667 =")
    cy.clickButton_equal()
    cy.check_answer("-24667")
    cy.check_history("0 - 24667 =")
    cy.clickButton_equal()
    cy.check_answer("-24667")
    cy.check_history("0 - 24667 =")
    cy.clickButton_equal()
    cy.AC_expected()
    cy.clickButton_AC_CE()
    cy.CE_expected()
    cy.clickButton_AC_CE()
    cy.clickButton_AC_CE()
    cy.clickButton_AC_CE()
    cy.clickButton_AC_CE()
    cy.clickButton_AC_CE()
    cy.CE_expected()


  })
})